# SPDX-FileCopyrightText: 2024 German Aerospace Center (DLR)
# SPDX-License-Identifier: CC0-1.0

version: '3.7'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: esid/frontend:${ESID_BRANCH}
    environment:
      HOST: ${HOST}
      API_URL: ${API_URL}
      PROXY_HOST: ${PROXY_HOST}
      PROXY_PORT: ${PROXY_PORT}
    ports:
      - ${ESID_PORT}:80
