# ! PLEASE NOTE THAT THIS IS ONLY FOR INTERNAL USE AND THE FILE IS UPLOADED ON GITHUB FOR CONVENIENCE

# The bellow pipeline allows to build and deploy the website automatically, whenever developer pushes code to the application.
# The building stage uses a predefined docker image to improve performance.

stages:
  - docker

ubuntu:publish-esid-apache-image:
  stage: docker
  tags:
    - shell
  script:
    - cd frontend
    - echo $ARTIFACTORY_TOKEN | docker login vcevis-common-docker-snapshot.artifacts.dlr.de -u $ARTIFACTORY_USER --password-stdin
    - docker image build -t vcevis-common-docker-snapshot.artifacts.dlr.de/esid:nginx-latest .
    - docker push vcevis-common-docker-snapshot.artifacts.dlr.de/esid:nginx-latest
