# SPDX-FileCopyrightText: 2024 German Aerospace Center (DLR)
# SPDX-License-Identifier: CC0-1.0

version: '3'
services:
  db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

  backend:
    image: esid/backend:latest
    restart: always
    env_file: backend/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DJANGO_DEBUG: 'False'
    build:
      context: backend/
      args:
        REQUIREMENTS_FILE: prod.txt
    ports:
      - 8000:8000
    volumes:
      - django-data:/localdata
    depends_on:
      - db

  frontend:
    image: esid/frontend:${ESID_BRANCH}
    restart: always
    build:
      context: frontend/
    environment:
      PROXY_HOST: backend
      PROXY_PORT: 8000
      HOST: ${HOST}
    ports:
      - ${ESID_PORT}:80
    depends_on:
      - backend

volumes:
  django-data:
    external: True
  postgres-data:
    external: True
  pgadmin-data:
    external: True
