version: '3'
services:
  db:
    image: postgres:13.3
    user: ${USER_ID}:${GROUP_ID}
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres-data:/data/postgres

  backend:
    image: esid/backend:latest
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DJANGO_DEBUG: 'False'
      DJANGO_SETTINGS_MODULE: 'src.config.production'
      DJANGO_SECRET_KEY: '#p7&kxb7y^yq8ahfw5%$xh=f8=&1y*5+a5($8w_f7kw!-qig(j'
      SITE_URL: ${SITE_URL}
    build:
      context: .
      args:
        REQUIREMENTS_FILE: prod.txt
    ports:
      - 8000:8000
    volumes:
      - django-data:/localdata
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '5050:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  django-data:
    external: True
  postgres-data:
    external: True
  pgadmin-data:
    external: True
