# SPDX-FileCopyrightText: 2024 German Aerospace Center (DLR)
# SPDX-License-Identifier: CC0-1.0

name: Epic
description: Create a new epic
title: "[EPIC]: "
projects: "DLR-SC/5"
labels: ["Epic"]
body:
  - type: checkboxes
    id: pre-steps
    attributes:
      label: Things to do durng epic creation
      options:
        - label: Add this Issue to the "ESID-Frontend" Project board
          required: true
        - label: Create a branch for this epic (`feature/short-name`) and add it in the development field
          required: true
        - label: Create sub issues as needed
          required: false
  - type: textarea
    id: details
    attributes:
      label: Details
      value: |
        <!-- Detailed description of the Epic, its requirements, and goals -->
        
        ---
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      value: |
        <!-- Notes on things that are out of scope of the Epic but may spawn new issues at a later date -->
