# SPDX-FileCopyrightText: 2024 German Aerospace Center (DLR)
# SPDX-License-Identifier: CC0-1.0

name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["class:bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your report!
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Provide a clear and concise description of the bug.
        If necessary, add screenshots to explain the problem.
        Provide steps to reproduce the problem.
      value: |
        Provide a clear and concise description of the bug.
        If necessary, add screenshots to explain the problem.
        
        Steps to reproduce the problem:
        1. Do this
        2. Do that
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Please describe what should happen instead.
      placeholder: A clear description of what you expected to happen.
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browser(s) are you using?
      multiple: true
      options:
        - Microsoft Edge
        - Chrome
        - Firefox
        - Safari
        - Opera
        - Internet Explorer
        - Other
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Browser Version (and name if 'other' was selected)
      placeholder: version number
    validations:
      required: false
