# SPDX-FileCopyrightText: 2024 German Aerospace Center (DLR)
# SPDX-License-Identifier: CC0-1.0

name: Epic
description: Create a new epic
title: "[EPIC]: "
labels: ["Epic"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      value: |
        <!--
        ToDo Epic Creation
        ==================
        Things to do during epic creation:
        - [ ] Create a Label with a short name for this epic like "Epic:ShortName" with the color "#4660F9"
          - Add this label to this Issue
        - [ ] Add Issue to the "ESID-Frontend" Project board and sort it into status "Epics"
        - [ ] Create a branch for this epic and add it int he Development field like "feature/short-name"
        -->
        ## Related Issues/Tasks:
        <!--
        Add a checkbox list (- [ ]) with the tasks needed for the Epic.
        replace them with issue links (#<issue number>) when the issues are created.
        i.e.:
        - [ ] Do thing for epic
        - [ ] #110
        -->
        ---
        ## Details
        <!-- Detailed description of the Epic, its requirements, and goals -->
        
        ---
        <!-- Notes on things that are out of scope of the Epic but may spawn new issues at a later date -->
    validations:
      required: true
