# Generated by Django 3.2.3 on 2022-01-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fill_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='percentile',
            field=models.IntegerField(default=50),
        ),
    ]
