# SPDX-FileCopyrightText: 2024 German Aerospace Center (DLR)
# SPDX-License-Identifier: CC0-1.0

name: Push

on: ["push"]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Setup
        run: npm install

      - name: Formatting
        run: npx prettier --check .

      - name: Linting
        run: npx eslint src

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
      - name: Upload Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: frontend/reports/vitest-junit.xml

      - name: Coverage
        run: npm run coverage
      - name: Upload Coverage
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: frontend/reports/clover.xml
          format: clover
          base-path: frontend
          
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: |
          cd frontend && npm install && npm install -g @lhci/cli@0.12.x
          npm run build
      - run: cd frontend && lhci autorun --collect.psiStrategy=desktop --upload.target=temporary-public-storage
    env:
      LHCI_GITHUB_APP_TOKEN: ${{ secrets.LIGHTHOUSE_CI }}

  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  reuse:
    name: Check Compliance with REUSE Specification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1
