name: Push

on: ["push", "pull_request"]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Setup
        run: npm install

      - name: Formatting
        run: npx prettier --check .

      - name: Linting
        run: npx eslint src

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
      - name: Upload Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: frontend/reports/jest-junit.xml

      - name: Coverage
        run: npm run coverage
      - name: Upload Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: frontend/reports/lcov.info
          base-path: frontend
          
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - if: ${{ github.event_name == 'pull_request' }}
        run: |
          cd frontend && npm install && npm install -g @lhci/cli@0.8.x
          npm run build
          lhci autorun --collect.psiStrategy=desktop --upload.target=temporary-public-storage
    env:
      LHCI_GITHUB_APP_TOKEN: ${{ secrets.LIGHTHOUSE_CI }}
