name: Push

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Setup
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
      - name: Upload Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: frontend/reports/jest-junit.xml

      - name: Coverage
        run: npm run coverage
      - name: Upload Coverage
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          working-directory: frontend
          coverage-files: reports/lcov.*.info
          minimum-coverage: 95
          artifact-name: frontend-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
