name: Push

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Setup
        run: |
          cd frontend
          npm install

      - name: Build
        run: |
          cd frontend
          npm run build

      - name: Test
        run:  |
          cd frontend
          npm run test
      - name: Upload Test Results
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: ./reports/jest-junit.xml

      - name: Coverage
        run:  |
          cd frontend
          npm run coverage
      - name: Upload Coverage
        uses: danhunsaker/clover-reporter-action@v0.2.17-clover
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clover-file: ./reports/clover.xml
